services:
  api:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    container_name: security-sample-api
    ports:
      - "5055:5055"
    environment:
      - NODE_ENV=prod
      - PORT=5055
      - DB_HOST=127.0.0.1:3306
      - DB_USER=sec_challenge_user
      - DB_PASSWORD=passwordchallenge
      - DB_DATABASE=nutrition
    restart: always
    networks:
      - sgbdr-network-prod
  mon_sgbdr:
    image: mariadb

networks:
  sgbdr-network-prod:
    driver: bridge
    name: sgbdr-network-prod
