FROM node:20-alpine AS api-builder
WORKDIR app
COPY . .
RUN yarn install
RUN yarn run clean
RUN yarn run build

FROM node:20-alpine AS api
WORKDIR app
COPY --from=api-builder /app/build ./
COPY package* ./
COPY assets/* ./assets/
RUN yarn install --omit=dev
CMD yarn run start-api